name: CI - Test & Build

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          [22.14.0]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # {2}
      - name: Checkout the source code
        uses: actions/checkout@v6

      # {3}
      - name: Setup Node.js 6
        uses: actions/setup-node@v6
        with:
          node-version: .nvmrc
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # {4}
      - name: Install dependencies
        run: npm ci
      # {5}
      - name: Run tests
        run: npm run test
      # {6}
      - name: Build
        run: npm run build
